version: "3"
services:
  postgres:
    image: "postgres:16.3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=airflow --dbname=airflow"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    container_name: "postgres"
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  airflow-initdb:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: airflow db init && airflow connections create-default-connections

  airflow-webserver:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/usr/local/airflow/dags
    entrypoint: airflow webserver

  airflow-scheduler:
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./dags:/usr/local/airflow/dags
    entrypoint: airflow scheduler

  redis:
    container_name: clickhouse-server
    ports:
      - "6379:6379"
    depends_on:
      - postgres
    image: redis:7.2-bookworm

  clickhouse-server:
    depends_on:
      - postgres
    image: "clickhouse/clickhouse-server:24.10.1.2812"
    container_name: clickhouse-server
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
    ulimits:
      nofile: 262144

