version: "3"
services:
  postgres:
    image: "postgres:16.3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=airflow --dbname=airflow"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    container_name: "postgres"
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  airflow-initdb:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_completed_successfully
    entrypoint: bash -c "airflow db init && \
                airflow connections create-default-connections && \
                airflow users create \
                --username admin \
                --firstname FIRST_NAME \
                --lastname LAST_NAME \
                --role Admin \
                --password admin
                --email admin@example.org &&
                airflow dags backfill lab05 -s 2020-11-20 -e 2020-11-30"


  airflow-webserver:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/usr/local/airflow/dags
    entrypoint: airflow webserver

  airflow-scheduler:
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./dags:/usr/local/airflow/dags
    entrypoint: airflow scheduler

  redis:
    container_name: "redis"
    ports:
      - "6379:6379"
    depends_on:
      - postgres
    image: redis:7.2-bookworm

  clickhouse-server:
    image: "clickhouse/clickhouse-server:24.10.1.2812"
    container_name: "clickhouse-server"
    depends_on:
      - postgres
    restart: always
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./users.xml:/etc/clickhouse-server/users.xml:ro
      - ./data/clickhouse:/var/lib/clickhouse
    ulimits:
      nofile: 262144
