version: "3"
services:
  postgres:
    image: "postgres:16.3"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  airflow-initdb:
    build: .
    depends_on:
      - postgres
    entrypoint: airflow db migrate && airflow connections create-default-connections}

  airflow-webserver:
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - "8080:8080"
    entrypoint: airflow webserver

  airflow-scheduler:
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./dags:/usr/local/airflow/dags
    entrypoint: airflow scheduler

  redis:
    depends_on:
      - postgres
    image: redis:7.2-bookworm
    ports:
      - "6379:6379"

  clickhouse-server:
    depends_on:
      - postgres
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
    ulimits:
      nofile: 262144

