version: "3"
services:
  postgres:
    network_mode: "host"
    image: "postgres:16.3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=airflow --dbname=airflow"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    container_name: "postgres"
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  airflow-initdb:
    network_mode: "host"
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: airflow db init && airflow connections create-default-connections

  airflow-webserver:
    network_mode: "host"
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./dags:/usr/local/airflow/dags
    entrypoint: airflow webserver

  airflow-scheduler:
    network_mode: "host"
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./dags:/usr/local/airflow/dags
    entrypoint: airflow scheduler

  redis:
    network_mode: "host"
    depends_on:
      - postgres
    image: redis:7.2-bookworm

  clickhouse-server:
    network_mode: "host"
    depends_on:
      - postgres
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
    ulimits:
      nofile: 262144

vitalii@vitalii-Katana-17-B12VFK:~/lab05/airflow$ 


